---
# file: oracle-java/meta/main.yml
#
# meta file
#

galaxy_info:
  author: Pedro Salgado
  description: Role to install Oracle Java.
  company: ansiblebit.org
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: CentOS
      versions:
        - all
        - any
        - 7
        - 6
    - name: Debian
      versions:
        - jessie
        - wheezy
    - name: RedHat
      versions:
        - all
        - any
        - 7
        - 6
    - name: Ubuntu
      versions:
        - xenial
        - vivid
        - trusty
        - precise
  galaxy_tags:
    - development
    - java
    - system
